import { League_Spartan } from "next/font/google";
import '@/styles/styles.scss';
import '@/styles/fontawesome/css/all.css';
import GlobalProvider from "./GlobalProvider";

const spartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Eliah - React NextJs Beauty Salon & Cosmetic Shop Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
          {children}
          <div id="nav-full" />
          <div id="nav-sidebar" />
          <div id="cart-sidebar" />
          <div id="overlay" />
          <div id="modal" />
        </GlobalProvider>
      </body>
    </html>
  );
}
